import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { buildStaffConfirmationEmail } from "./vocal-session-email";
import { buildGoogleCalendarUrl, buildIcsAttachment, buildIcsFile } from "./calendar-invite";

const confirmInput = z.object({
  requestId: z.string().uuid(),
  slot: z.object({ date: z.string().min(1).max(20), time: z.string().min(1).max(10) }),
});

/** Staff-only: approve one proposed slot and hand back the session's video-chat link. */
export const confirmVocalSessionSlot = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .validator((data: unknown) => confirmInput.parse(data))
  .handler(async ({ data, context }) => {
    // Role check runs server-side against the DB through the caller's
    // RLS-scoped client — never against anything the browser asserts.
    const { data: roles } = await context.supabase
      .from("user_roles")
      .select("role")
      .eq("user_id", context.userId)
      .in("role", ["admin", "staff"]);
    if (!roles || roles.length === 0) throw new Error("Forbidden");

    const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
    const { data: row, error } = await supabaseAdmin
      .from("vocal_session_requests")
      .update({
        status: "confirmed",
        confirmed_slot: data.slot,
        confirmed_at: new Date().toISOString(),
      })
      .eq("id", data.requestId)
      .select("id, artist, email, timezone, package_label, meeting_link, confirmed_slot")
      .single();

    if (error || !row) throw new Error(error?.message ?? "Session request not found");

    // The meeting link is generated by the database when the request is created,
    // so every approved slot already has a room waiting for it.
    const email = buildStaffConfirmationEmail({
      artist: row.artist,
      timezone: row.timezone,
      packageLabel: row.package_label,
      slot: data.slot,
      meetingLink: row.meeting_link ?? "",
    });

    // Artist-facing status update goes out automatically on approval.
    const { buildSessionStatusEmail } = await import("./vocal-session-email");
    const { sendSessionEmail, STAFF_NOTIFY_TO } = await import("./session-mailer.server");
    const artistEmail = buildSessionStatusEmail({
      artist: row.artist,
      status: "confirmed",
      timezone: row.timezone,
      packageLabel: row.package_label,
      slot: data.slot,
      meetingLink: row.meeting_link,
    });
    // Confirmed slots ship with a calendar invite the artist can open directly.
    const invite = buildIcsAttachment({
      artist: row.artist,
      slot: data.slot,
      timezone: row.timezone,
      packageLabel: row.package_label,
      meetingLink: row.meeting_link,
      uid: row.id,
    });

    const mail = await sendSessionEmail({
      to: [row.email, STAFF_NOTIFY_TO],
      subject: artistEmail.subject,
      html: artistEmail.html,
      text: artistEmail.text,
      ...(invite ? { attachments: [invite] } : {}),
      log: { requestId: row.id, kind: "confirmed", slot: data.slot },
    });

    return {
      mail,
      requestId: row.id,
      artistEmail: row.email,
      meetingLink: row.meeting_link,
      confirmationEmail: email,
      calendar: {
        googleUrl: buildGoogleCalendarUrl({
          artist: row.artist,
          slot: data.slot,
          timezone: row.timezone,
          packageLabel: row.package_label,
          meetingLink: row.meeting_link,
        }),
        ics: buildIcsFile({
          artist: row.artist,
          slot: data.slot,
          timezone: row.timezone,
          packageLabel: row.package_label,
          meetingLink: row.meeting_link,
          uid: row.id,
        }),
      },
    };
  });
