import { useEffect } from "react";
import { X } from "lucide-react";

interface Props {
  open: boolean;
  onClose: () => void;
}

type Block = { text: string } | { list: string[] };

const SECTIONS: { num: string; heading: string; blocks: Block[] }[] = [
  {
    num: "01",
    heading: "Overview of Services",
    blocks: [
      {
        text: "Hybrid AI Records LLC provides independent music production, audio mastering, video generation, and label distribution services designed around 10-track album projects. Our packages include:",
      },
      {
        list: [
          "The Foundation: Audio hosting, formatting, and digital distribution across major streaming platforms.",
          "The Visual Push: Complete 10-track album production plus 1 official music video delivered upon project completion.",
          "The Full Hybrid Experience: Complete 10-track album production, 2 official music videos delivered upon project completion, and digital distribution under our label backing.",
        ],
      },
    ],
  },
  {
    num: "02",
    heading: "Intellectual Property & Royalty Rights",
    blocks: [
      {
        list: [
          "100% Artist Ownership: You retain full ownership, copyright, and 100% of master earnings and royalties generated by your original lyrics, vocal performances, and concepts.",
          "License to Produce: By submitting content (lyrics, audio stems, vocal recordings) to us, you grant Hybrid AI Records LLC a non-exclusive, worldwide license to process, produce, mix, master, and format your assets solely for the purpose of fulfilling your selected service package.",
          "Originality Guarantee: You represent and warrant that all lyrics, samples, and media submitted to us are your original work or that you hold the necessary licenses and permissions to use them.",
        ],
      },
    ],
  },
  {
    num: "03",
    heading: "Submission & Project Approval Workflow",
    blocks: [
      {
        list: [
          "Pre-Payment Review: All song lyrics, concepts, and audio files must be submitted via our application form for review prior to final invoice generation or production kickoff.",
          "Right of Refusal: We reserve the right to decline any submission that promotes illegal activity, hate speech, or severe copyright infringement.",
        ],
      },
    ],
  },
  {
    num: "04",
    heading: "Media Creation & Non-Refundable Video Policy",
    blocks: [
      {
        list: [
          "Album Completion Requirement: Official music video production for The Visual Push and The Full Hybrid Experience packages begins only upon completion of the full 10-track album project.",
          "Finalized Media Policy: Due to the intensive computing power and engineering required for AI audio rendering and video generation, all video and rendered media production is finalized upon completion and strictly non-refundable once rendering or production begins.",
        ],
      },
    ],
  },
  {
    num: "05",
    heading: "Payments, Fees & Invoicing",
    blocks: [
      { text: "All service fees are outlined on our website and billed according to the agreed package structure." },
      { text: "Payments must be processed through our authorized payment gateways prior to final master file delivery or official digital distribution release." },
    ],
  },
  {
    num: "06",
    heading: "Limitation of Liability",
    blocks: [
      {
        text: "To the maximum extent permitted by applicable law, Hybrid AI Records LLC shall not be liable for any indirect, incidental, consequential, or punitive damages arising out of your use of our services, third-party streaming service delays, or platform downtime.",
      },
    ],
  },
  {
    num: "07",
    heading: "Governing Law",
    blocks: [
      {
        text: "These Terms shall be governed by and construed in accordance with the laws of the State of Tennessee, without regard to its conflict of law principles.",
      },
    ],
  },
  {
    num: "08",
    heading: "Contact Information",
    blocks: [
      { text: "If you have any questions regarding these Terms, please contact us at:" },
      { text: "Hybrid AI Records LLC" },
      { text: "Official Email: Hybrid.AI.Records@proton.me" },
    ],
  },
];

export function TermsModal({ open, onClose }: Props) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") onClose();
    };
    document.body.style.overflow = "hidden";
    window.addEventListener("keydown", onKey);
    return () => {
      document.body.style.overflow = "";
      window.removeEventListener("keydown", onKey);
    };
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-label="Terms of Service"
      className="fixed inset-0 z-[110] flex flex-col studio-glass lg:ps-[var(--site-sidebar-width)]"
      onClick={onClose}
    >
      <div
        className="relative mx-auto flex h-full w-full max-w-3xl flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/60 bg-white/70 px-6 py-4 backdrop-blur-md sm:px-10">
          <div className="min-w-0">
            <div className="font-mono text-[10px] uppercase tracking-[0.24em] text-muted-foreground">
              <span className="text-[#e11d2e]">/</span>{" "}
              <span className="text-white">Terms of</span>{" "}
              <span className="text-[#4b8bff]">Service</span>
            </div>
            <div className="mt-1 truncate font-display text-sm font-semibold sm:text-base">
              Hybrid AI Records LLC
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close terms of service"
            className="grid h-10 w-10 shrink-0 place-items-center border border-border text-foreground transition-colors hover:border-primary hover:text-primary"
          >
            <X size={18} />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto px-6 py-10 sm:px-10 sm:py-14">
          <header className="border-b border-border pb-10">
            <div className="font-mono text-[10px] uppercase tracking-[0.24em] text-muted-foreground">
              <span className="text-[#e11d2e]">HYBRID</span>{" "}
              <span className="text-white">AI</span>{" "}
              <span className="text-[#4b8bff]">RECORDS LLC</span>
            </div>
            <h2 className="mt-4 font-display text-3xl font-semibold leading-tight tracking-tight text-white sm:text-4xl md:text-5xl">
              Terms of Service
            </h2>
            <div className="mt-6 grid gap-2 font-mono text-[11px] uppercase tracking-[0.22em] text-muted-foreground sm:grid-cols-2">
              <div>
                <span className="text-[#e11d2e]">Effective Date:</span>{" "}
                <span className="text-white">May 28, 2026</span>
              </div>
              <div>
                <span className="text-[#4b8bff]">Last Updated:</span>{" "}
                <span className="text-white">July 24, 2026</span>
              </div>
            </div>
            <p className="mt-6 text-[15px] leading-relaxed text-muted-foreground sm:text-base sm:leading-[1.75]">
              Welcome to Hybrid AI Records LLC ("Company," "we," "us," or "our"). These Terms of
              Service ("Terms") govern your access to and use of our website, production services,
              label distribution, and visual media creation (collectively, "Services").
            </p>
            <p className="mt-4 text-[15px] leading-relaxed text-muted-foreground sm:text-base sm:leading-[1.75]">
              By accessing our website, submitting lyrics, voice tracks, or audio files, or
              purchasing any service package, you agree to be bound by these Terms. If you do not
              agree, please do not use our Services.
            </p>
          </header>

          <div className="space-y-12 pt-10">
            {SECTIONS.map((s) => (
              <section key={s.num} className="border-b border-border/60 pb-10 last:border-b-0">
                <div className="font-mono text-[10px] uppercase tracking-[0.24em] text-[#e11d2e]">
                  / {s.num}
                </div>
                <h2 className="mt-3 font-display text-2xl font-semibold leading-tight tracking-tight text-white sm:text-3xl">
                  {s.heading}
                </h2>
                <div className="mt-5 space-y-4 text-[15px] leading-relaxed text-muted-foreground sm:text-base sm:leading-[1.75]">
                  {s.blocks.map((b, i) =>
                    "text" in b ? (
                      <p key={i}>{b.text}</p>
                    ) : (
                      <ul key={i} className="space-y-3 ps-0">
                        {b.list.map((item, j) => (
                          <li key={j} className="flex gap-3">
                            <span className="mt-2 h-px w-4 shrink-0 bg-[#e11d2e]" />
                            <span>{item}</span>
                          </li>
                        ))}
                      </ul>
                    ),
                  )}
                </div>
              </section>
            ))}
          </div>

          <div className="mt-12 flex justify-center">
            <button
              type="button"
              onClick={onClose}
              className="border border-white px-8 py-3 text-xs font-semibold uppercase tracking-widest text-white transition-colors hover:bg-white hover:text-black"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
